sudo: false
language: go
before_script:
  - go get bitbucket.org/liamstask/goose/cmd/goose
  - cd server && goose -env="test" up && cd ../
script: go test -v ./...
go:
  - 1.4
  - 1.5
  - 1.6
  - tip
matrix:
  allow_failures:
    - go: tip
